name: Component Versions Request
description: Submit desired versions for Kubernetes components
title: "[Component Versions] "
labels: ["component-versions"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please provide the desired versions for each component below.

  - type: input
    id: kubernetes_helm_version
    attributes:
      label: "Kubernetes Helm Version"
      description: "Desired Helm version (e.g., v3.8.2)"
      placeholder: "v3.8.2"
    validations:
      required: true

  - type: input
    id: etcd_etcd_version
    attributes:
      label: "ETCD Version"
      description: "Desired ETCD version (e.g., v3.5.4)"
      placeholder: "v3.5.4"
    validations:
      required: true

  - type: input
    id: image_registry_keepalived_version
    attributes:
      label: "Keepalived Version"
      description: "Desired Keepalived version (e.g., 2.0.20)"
      placeholder: "2.0.20"
    validations:
      required: true

  # 添加更多组件字段...
  # 为了简洁，这里只展示了部分字段
  # 实际使用时需要添加所有需要的字段

  - type: input
    id: dns_dns_cache_image_tag
    attributes:
      label: "DNS Cache Image Tag"
      description: "Desired DNS cache image tag (e.g., 1.21.1)"
      placeholder: "1.21.1"
    validations:
      required: true
